translations=["ASV","AKJV","BRG","EHV","ESV","ESVUK","GNV","GW","ISV",
              "JUB","KJV","KJ21","LEB","MEV","NASB","NASB1995","NET",
              "NIV","NIVUK","NKJV","NLT","NLV","NOG","NRSV","NRSVUE","WEB","YLT"]

bibleVersions={
    "ASV":"American Standard Version",
    "AKJV":"Authorized King James Version",
    "BRG":"BRG Bible",
    "EHV":"Evangelical Heritage Version",
    "ESV":"English Standard Version",
    "ESVUK":"English Standard Version Anglicised",
    "GNV":"Geneva Bible",
    "GW":"God's Word",
    "ISV":"International Standard Version",
    "JUB":"Jubilee Bible",
    "KJV":"King James Version",
    "KJ21":"21st Century King James Version",
    "LEB":"Lexham English Bible",
    "MEV":"Modern English Version",
    "NASB":"New American Standard Bible",
    "NASB1995":"New American Standard Bible 1995 Edition",
    "NET":"New English Translation",
    "NIV":"New International Version",
    "NIVUK":"New International Version UK",
    "NKJV":"New King James Version",
    "NLT":"New Living Translation",
    "NLV":"New Life Version",
    "NOG":"Names of God Bible",
    "NRSV":"New Revised Standard Version",
    "NRSVUE":"New Revised Standard Version Updated Edition",
    "WEB":"World English Bible",
    "YLT":"Young's Literal Translation of the Bible"
}
